dbname: Test # В классе менять не надо
user:  postgres # Замените на свой логин от БД в классе
password: Qwerty # Замените на свой пароль от БД в классе
host: localhost # Замените на 192.168.0.48 в классе
dbtableprefix: "public."  # Замените на свой логин от БД